import React,{useMemo,useState} from 'react';
import {CalendarOff,Clock,Save,Trash2} from 'lucide-react';
import {useApp} from '../../context/AppContext';
const days=['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'];
const defaults=()=>days.map((_,weekday)=>({weekday,startTime:'09:00',endTime:'19:00',breakStart:'12:00',breakEnd:'13:00',active:weekday!==0}));
const BarberAvailability:React.FC=()=>{
 const {currentUser,professionals,saveProfessionalSchedule,addProfessionalTimeOff,removeProfessionalTimeOff}=useApp();
 const me=professionals.find(p=>p.id===currentUser?.professionalId)||professionals.find(p=>p.userId===currentUser?.id)||null;
 const initial=useMemo(()=>{const base=defaults();for(const h of me?.workingHours||[])base[h.weekday]={...base[h.weekday],...h};return base},[me?.id,me?.workingHours]);
 const [hours,setHours]=useState<any[]>(initial);const [block,setBlock]=useState({date:'',startTime:'09:00',endTime:'19:00',reason:''});
 React.useEffect(()=>setHours(initial),[initial]);
 if(!me)return <div className="empty-state"><h2 className="text-white font-bold">Perfil profissional não vinculado</h2><p className="mt-2 text-sm">Peça ao administrador para vincular seu acesso ao cadastro de profissional.</p></div>;
 const addBlock=async()=>{if(!block.date)return;if(await addProfessionalTimeOff({professionalId:me.id,...block}))setBlock({date:'',startTime:'09:00',endTime:'19:00',reason:''})};
 return <div className="space-y-7 pb-10"><div><p className="eyebrow">Minha operação</p><h1 className="page-title mt-2">Minha disponibilidade</h1><p className="page-subtitle">Defina sua jornada, intervalo e bloqueios. Esses dados alimentam os horários reais disponíveis aos clientes.</p></div>
 <section className="surface p-6 space-y-4"><h2 className="section-title flex items-center gap-2"><Clock size={19} className="text-amber-500"/>Jornada semanal</h2>{hours.map((h,i)=><div key={h.weekday} className="grid md:grid-cols-[120px_70px_1fr_1fr_1fr_1fr] gap-2 items-center border-b border-white/5 pb-3"><span className="text-sm text-slate-300">{days[h.weekday]}</span><input type="checkbox" checked={h.active} onChange={e=>setHours(hours.map((x,j)=>j===i?{...x,active:e.target.checked}:x))}/><input type="time" disabled={!h.active} value={h.startTime} onChange={e=>setHours(hours.map((x,j)=>j===i?{...x,startTime:e.target.value}:x))} className="field"/><input type="time" disabled={!h.active} value={h.endTime} onChange={e=>setHours(hours.map((x,j)=>j===i?{...x,endTime:e.target.value}:x))} className="field"/><input type="time" disabled={!h.active} value={h.breakStart||''} onChange={e=>setHours(hours.map((x,j)=>j===i?{...x,breakStart:e.target.value}:x))} className="field"/><input type="time" disabled={!h.active} value={h.breakEnd||''} onChange={e=>setHours(hours.map((x,j)=>j===i?{...x,breakEnd:e.target.value}:x))} className="field"/></div>)}<button onClick={()=>saveProfessionalSchedule(me.id,hours)} className="btn-primary"><Save size={18}/>Salvar minha jornada</button></section>
 <section className="surface p-6 space-y-4"><h2 className="section-title flex items-center gap-2"><CalendarOff size={19} className="text-violet-400"/>Folgas e bloqueios</h2><div className="grid md:grid-cols-4 gap-2"><input type="date" value={block.date} onChange={e=>setBlock({...block,date:e.target.value})} className="field"/><input type="time" value={block.startTime} onChange={e=>setBlock({...block,startTime:e.target.value})} className="field"/><input type="time" value={block.endTime} onChange={e=>setBlock({...block,endTime:e.target.value})} className="field"/><input placeholder="Motivo (opcional)" value={block.reason} onChange={e=>setBlock({...block,reason:e.target.value})} className="field"/></div><button onClick={addBlock} className="btn-secondary">Adicionar bloqueio</button><div className="space-y-2">{(me.timeOff||[]).map(o=><div key={o.id} className="flex justify-between items-center p-3 bg-slate-900 rounded-xl"><div className="text-sm text-slate-300">{new Date(o.startsAt).toLocaleString('pt-BR')} — {new Date(o.endsAt).toLocaleString('pt-BR')} {o.reason&&<span className="text-slate-500">· {o.reason}</span>}</div><button onClick={()=>removeProfessionalTimeOff(me.id,o.id)} className="text-red-400"><Trash2 size={17}/></button></div>)}{!(me.timeOff||[]).length&&<p className="text-sm text-slate-500">Nenhum bloqueio cadastrado.</p>}</div></section></div>;
};
export default BarberAvailability;