import React from 'react';
import {useApp} from '../../context/AppContext';
import {Users,CalendarDays,Clock3,DollarSign,TrendingUp,UserCheck,ArrowUpRight,ChevronRight,Wallet,Star} from 'lucide-react';
import {ResponsiveContainer,AreaChart,Area,XAxis,YAxis,Tooltip,CartesianGrid} from 'recharts';

const money=(v:number)=>`R$ ${v.toLocaleString('pt-BR',{minimumFractionDigits:2})}`;
const AdminDashboard:React.FC=()=>{
 const {bookings,users,services,professionals,settings}=useApp(); const now=new Date(); const today=now.toISOString().slice(0,10); const month=now.toISOString().slice(0,7);
 const clients=users.filter(u=>u.role==='client'); const todayBookings=bookings.filter(b=>b.date===today&&b.status!=='cancelled').sort((a,b)=>a.time.localeCompare(b.time));
 const monthFinished=bookings.filter(b=>b.date.startsWith(month)&&b.status==='finished'); const revenue=monthFinished.reduce((s,b)=>s+b.servicePrice,0); const todayRevenue=bookings.filter(b=>b.date===today&&b.status==='finished').reduce((s,b)=>s+b.servicePrice,0);
 const avg=monthFinished.length?revenue/monthFinished.length:0; const pending=bookings.filter(b=>b.status==='pending').length;
 const days=Array.from({length:7},(_,i)=>{const d=new Date(now);d.setDate(now.getDate()-6+i);const key=d.toISOString().slice(0,10);return {label:d.toLocaleDateString('pt-BR',{weekday:'short'}).replace('.',''),value:bookings.filter(b=>b.date===key&&b.status==='finished').reduce((s,b)=>s+b.servicePrice,0)}});
 const stats=[['Receita no mês',money(revenue),DollarSign,'text-emerald-400'],['Atendimentos no mês',monthFinished.length,CalendarDays,'text-blue-400'],['Ticket médio',money(avg),Wallet,'text-amber-400'],['Clientes ativos',clients.length,Users,'text-violet-400']];
 return <div className="space-y-7 pb-10">
  <header className="flex flex-col sm:flex-row sm:items-end justify-between gap-4 pt-2"><div><p className="text-amber-500 text-[10px] uppercase tracking-[.28em] font-bold">Central de gestão</p><h1 className="text-3xl lg:text-4xl font-serif font-bold text-white mt-2">Olá, {users.find(u=>u.id==='admin-1')?.name?.split(' ')[0]||'Admin'}.</h1><p className="text-slate-500 mt-1">Aqui está o desempenho da sua barbearia.</p></div><div className="text-sm text-slate-500 bg-slate-900 border border-white/5 px-4 py-2.5 rounded-xl">{now.toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'})}</div></header>
  <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4">{stats.map(([label,value,Icon,cls]:any)=><div key={label} className="rounded-2xl bg-slate-900 border border-white/5 p-5 hover:border-white/10 transition"><div className="flex justify-between"><span className="text-xs text-slate-500 uppercase tracking-wider font-bold">{label}</span><Icon size={19} className={cls}/></div><div className="text-2xl font-bold text-white mt-4">{value}</div><div className="text-[11px] text-slate-600 mt-2">{label==='Receita no mês'?`${todayRevenue?money(todayRevenue)+' hoje':'Sem receita hoje'}`:label==='Atendimentos no mês'?`${pending} aguardando confirmação`:'Atualizado em tempo real'}</div></div>)}</div>
  <div className="grid lg:grid-cols-3 gap-5">
   <div className="lg:col-span-2 rounded-3xl bg-slate-900 border border-white/5 p-6"><div className="flex justify-between items-center mb-6"><div><h2 className="font-bold text-lg">Receita</h2><p className="text-xs text-slate-500">Últimos 7 dias · atendimentos finalizados</p></div><TrendingUp className="text-emerald-400" size={20}/></div><div className="h-64"><ResponsiveContainer width="100%" height="100%"><AreaChart data={days}><defs><linearGradient id="rev" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#f59e0b" stopOpacity={.25}/><stop offset="95%" stopColor="#f59e0b" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#1e293b" vertical={false}/><XAxis dataKey="label" stroke="#64748b" fontSize={11} axisLine={false} tickLine={false}/><YAxis stroke="#64748b" fontSize={11} axisLine={false} tickLine={false}/><Tooltip contentStyle={{background:'#0f172a',border:'1px solid #334155',borderRadius:12}} formatter={(v:any)=>money(Number(v))}/><Area type="monotone" dataKey="value" stroke="#f59e0b" strokeWidth={3} fill="url(#rev)"/></AreaChart></ResponsiveContainer></div></div>
   <div className="rounded-3xl bg-slate-900 border border-white/5 p-6"><div className="flex justify-between items-center"><div><h2 className="font-bold text-lg">Agenda de hoje</h2><p className="text-xs text-slate-500">{todayBookings.length} horários</p></div><Clock3 className="text-amber-400" size={20}/></div><div className="mt-5 space-y-2 max-h-64 overflow-auto custom-scrollbar">{todayBookings.slice(0,7).map(b=><div key={b.id} className="p-3 rounded-xl bg-white/[.03] border border-white/5 flex items-center gap-3"><div className="text-amber-400 font-bold text-sm w-11">{b.time}</div><div className="w-8 h-8 rounded-full bg-amber-500/10 flex items-center justify-center text-amber-400 text-xs font-bold">{b.userName[0]}</div><div className="min-w-0 flex-1"><div className="text-sm font-semibold truncate">{b.userName}</div><div className="text-[10px] text-slate-500 truncate">{b.serviceName} · {b.professionalName.split(' ')[0]}</div></div><span className={`w-2 h-2 rounded-full ${b.status==='confirmed'?'bg-blue-400':b.status==='pending'?'bg-amber-400':'bg-emerald-400'}`}/></div>)}{!todayBookings.length&&<div className="py-16 text-center text-slate-600 text-sm">Nenhum atendimento hoje.</div>}</div></div>
  </div>
  <div className="grid md:grid-cols-3 gap-5">
   <div className="md:col-span-2 rounded-3xl bg-slate-900 border border-white/5 p-6"><div className="flex justify-between items-center mb-5"><h2 className="font-bold">Performance por profissional</h2><UserCheck className="text-violet-400" size={19}/></div><div className="grid sm:grid-cols-3 gap-3">{professionals.map(p=>{const bs=monthFinished.filter(b=>b.professionalId===p.id);const total=bs.reduce((s,b)=>s+b.servicePrice,0);return <div key={p.id} className="rounded-2xl border border-white/5 bg-white/[.02] p-4"><div className="flex items-center gap-3"><img src={p.avatar} className="w-10 h-10 rounded-full object-cover" alt={p.name}/><div className="min-w-0"><div className="text-sm font-bold truncate">{p.name}</div><div className="text-[10px] text-slate-600">{bs.length} atendimentos</div></div></div><div className="mt-5 text-lg font-bold text-amber-400">{money(total)}</div></div>})}</div></div>
   <div className="rounded-3xl bg-gradient-to-br from-amber-500 to-amber-600 text-slate-950 p-6 relative overflow-hidden"><div className="absolute -right-10 -bottom-10 w-40 h-40 rounded-full bg-white/10"/><Star fill="currentColor" size={25}/><h2 className="font-serif text-2xl font-bold mt-5">Reputação</h2><p className="text-slate-900/70 text-sm mt-2">Avaliações ajudam a transformar clientes em recorrentes.</p><div className="mt-6 text-3xl font-bold">{bookings.filter(b=>b.rating).length}</div><div className="text-xs font-bold uppercase tracking-widest text-slate-900/60">avaliações recebidas</div></div>
  </div>
 </div>
};
export default AdminDashboard;
