import React,{useMemo,useState} from 'react';
import {useApp} from '../../context/AppContext';
import {CalendarOff,Clock,Plus,Save,Scissors,Trash2,UserRound} from 'lucide-react';
const days=['Domingo','Segunda','Terça','Quarta','Quinta','Sexta','Sábado'];
const defaults=()=>days.map((_,weekday)=>({weekday,startTime:'09:00',endTime:'19:00',breakStart:'12:00',breakEnd:'13:00',active:weekday!==0}));
const AdminProfessionals:React.FC=()=>{
 const {professionals,addProfessional,updateProfessional,saveProfessionalSchedule,addProfessionalTimeOff,removeProfessionalTimeOff}=useApp();
 const [form,setForm]=useState({name:'',role:'Barbeiro',specialty:'',avatar:'',createAccess:false,email:'',phone:'',password:''});const [selectedId,setSelectedId]=useState<string|null>(null);
 const selected=professionals.find(p=>p.id===selectedId)||null;
 const initial=useMemo(()=>{const base=defaults();for(const h of selected?.workingHours||[])base[h.weekday]={...base[h.weekday],...h};return base},[selectedId,selected?.workingHours]);
 const [hours,setHours]=useState<any[]>(initial);const [block,setBlock]=useState({date:'',startTime:'09:00',endTime:'19:00',reason:''});
 React.useEffect(()=>setHours(initial),[initial]);
 const create=async(e:React.FormEvent)=>{e.preventDefault();if(await addProfessional(form))setForm({name:'',role:'Barbeiro',specialty:'',avatar:'',createAccess:false,email:'',phone:'',password:''})};
 const addBlock=async()=>{if(!selected||!block.date)return;if(await addProfessionalTimeOff({professionalId:selected.id,...block}))setBlock({date:'',startTime:'09:00',endTime:'19:00',reason:''})};
 return <div className="space-y-7"><div><h1 className="page-title">Equipe</h1><p className="page-subtitle">Profissionais, jornadas, intervalos e indisponibilidades.</p></div>
 <div className="grid xl:grid-cols-[1fr_1.6fr] gap-6"><div className="space-y-5">
  <form onSubmit={create} className="glass border border-slate-700 rounded-3xl p-6 space-y-3"><h2 className="font-bold text-white flex gap-2"><Plus size={19} className="text-amber-500"/>Novo profissional</h2>
   <input required placeholder="Nome" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="field"/>
   <input placeholder="Função" value={form.role} onChange={e=>setForm({...form,role:e.target.value})} className="field"/>
   <input placeholder="Especialidade" value={form.specialty} onChange={e=>setForm({...form,specialty:e.target.value})} className="field"/>
   <input placeholder="URL da foto (opcional)" value={form.avatar} onChange={e=>setForm({...form,avatar:e.target.value})} className="field"/>
   <label className="flex items-center gap-3 text-sm text-slate-300"><input type="checkbox" checked={form.createAccess} onChange={e=>setForm({...form,createAccess:e.target.checked})}/>Criar acesso ao painel para este barbeiro</label>
   {form.createAccess&&<div className="space-y-2 p-4 rounded-2xl bg-slate-900 border border-slate-700"><input required type="email" placeholder="E-mail de acesso" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} className="field"/><input placeholder="Telefone (opcional)" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} className="field"/><input required minLength={8} type="password" placeholder="Senha inicial (8+)" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} className="field"/><p className="text-[11px] text-slate-500">O barbeiro verá somente a própria agenda vinculada a este perfil.</p></div>}
   <button className="w-full bg-amber-500 text-slate-950 rounded-xl py-3 font-bold">Adicionar profissional</button>
  </form>
  <div className="space-y-3">{professionals.map(p=><button key={p.id} onClick={()=>setSelectedId(p.id)} className={`w-full text-left p-4 rounded-2xl border ${selectedId===p.id?'border-amber-500 bg-amber-500/10':'border-slate-700 bg-slate-900/60'}`}><div className="flex items-center justify-between"><div className="flex gap-3 items-center"><div className="w-10 h-10 rounded-xl bg-slate-800 flex items-center justify-center"><UserRound size={19}/></div><div><div className="font-bold text-white">{p.name}</div><div className="text-xs text-slate-500">{p.role}{p.specialty?` · ${p.specialty}`:''}</div></div></div><span className={`text-xs font-bold ${p.active!==false?'text-emerald-400':'text-slate-500'}`}>{p.active!==false?'ATIVO':'INATIVO'}</span></div></button>)}{!professionals.length&&<div className="empty-state"><UserRound size={34} className="mx-auto mb-3 opacity-40"/><h3 className="text-white font-bold">Equipe vazia</h3><p className="text-xs mt-2">Cadastre o primeiro profissional para configurar sua jornada e liberar horários.</p></div>}</div>
 </div>
 <div>{selected?<div className="space-y-7 pb-10">
  <div className="glass border border-slate-700 rounded-3xl p-6"><div className="flex justify-between gap-4 items-center"><div><h2 className="text-xl font-bold text-white">{selected.name}</h2><p className="text-sm text-slate-500">Configuração operacional</p></div><button onClick={()=>updateProfessional(selected.id,{active:selected.active===false})} className="px-4 py-2 rounded-xl border border-slate-700 text-sm text-white">{selected.active===false?'Reativar':'Desativar'}</button></div></div>
  <div className="glass border border-slate-700 rounded-3xl p-6 space-y-4"><h2 className="font-bold text-white flex gap-2"><Clock size={19} className="text-amber-500"/>Jornada semanal</h2>{hours.map((h,i)=><div key={h.weekday} className="grid md:grid-cols-[120px_70px_1fr_1fr_1fr_1fr] gap-2 items-center border-b border-slate-800 pb-3"><span className="text-sm text-slate-300">{days[h.weekday]}</span><input type="checkbox" checked={h.active} onChange={e=>setHours(hours.map((x,j)=>j===i?{...x,active:e.target.checked}:x))}/><input type="time" disabled={!h.active} value={h.startTime} onChange={e=>setHours(hours.map((x,j)=>j===i?{...x,startTime:e.target.value}:x))} className="field"/><input type="time" disabled={!h.active} value={h.endTime} onChange={e=>setHours(hours.map((x,j)=>j===i?{...x,endTime:e.target.value}:x))} className="field"/><input type="time" disabled={!h.active} value={h.breakStart||''} onChange={e=>setHours(hours.map((x,j)=>j===i?{...x,breakStart:e.target.value}:x))} className="field"/><input type="time" disabled={!h.active} value={h.breakEnd||''} onChange={e=>setHours(hours.map((x,j)=>j===i?{...x,breakEnd:e.target.value}:x))} className="field"/></div>)}<button onClick={()=>saveProfessionalSchedule(selected.id,hours)} className="bg-amber-500 text-slate-950 px-5 py-3 rounded-xl font-bold flex gap-2"><Save size={18}/>Salvar jornada</button></div>
  <div className="glass border border-slate-700 rounded-3xl p-6 space-y-4"><h2 className="font-bold text-white flex gap-2"><CalendarOff size={19} className="text-violet-400"/>Bloqueios e folgas</h2><div className="grid md:grid-cols-4 gap-2"><input type="date" value={block.date} onChange={e=>setBlock({...block,date:e.target.value})} className="field"/><input type="time" value={block.startTime} onChange={e=>setBlock({...block,startTime:e.target.value})} className="field"/><input type="time" value={block.endTime} onChange={e=>setBlock({...block,endTime:e.target.value})} className="field"/><input placeholder="Motivo" value={block.reason} onChange={e=>setBlock({...block,reason:e.target.value})} className="field"/></div><button onClick={addBlock} className="px-4 py-2 rounded-xl bg-violet-500/15 text-violet-300 font-bold">Adicionar bloqueio</button><div className="space-y-2">{(selected.timeOff||[]).map(o=><div key={o.id} className="flex justify-between items-center p-3 bg-slate-900 rounded-xl"><div className="text-sm text-slate-300">{new Date(o.startsAt).toLocaleString('pt-BR')} — {new Date(o.endsAt).toLocaleString('pt-BR')} {o.reason&&<span className="text-slate-500">· {o.reason}</span>}</div><button onClick={()=>removeProfessionalTimeOff(selected.id,o.id)} className="text-red-400"><Trash2 size={17}/></button></div>)}</div></div>
 </div>:<div className="glass border border-slate-700 rounded-3xl p-12 text-center text-slate-500"><Scissors size={40} className="mx-auto mb-3"/>Selecione um profissional para configurar a agenda.</div>}</div></div>
 </div>
};
export default AdminProfessionals;
