import React,{useState} from 'react';
import {useApp} from '../../context/AppContext';
import {Plus,Trash2,Clock,X,Star,Edit2,Scissors,Layers3} from 'lucide-react';
import {Service} from '../../types';
const presets=['Corte','Barba','Sobrancelha','Corte + Barba','Corte + Sobrancelha','Corte + Barba + Sobrancelha'];
const categories=['Cabelo','Barba','Acabamento','Combo','Outros'];
const empty:Omit<Service,'id'>={name:'',price:0,duration:30,description:'',category:'Cabelo',isCombo:false,comboItems:[],active:true};
const AdminServices:React.FC=()=>{
 const {services,addService,updateService,removeService,bookings}=useApp();const [open,setOpen]=useState(false);const [editing,setEditing]=useState<string|null>(null);const [deleting,setDeleting]=useState<Service|null>(null);const [form,setForm]=useState<Omit<Service,'id'>>(empty);const [item,setItem]=useState('');
 const edit=(s?:Service)=>{setEditing(s?.id||null);setForm(s?{name:s.name,price:s.price,duration:s.duration,description:s.description||'',category:s.category||'Outros',isCombo:s.isCombo===true,comboItems:s.comboItems||[],active:s.active!==false}:{...empty,comboItems:[]});setOpen(true)};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(form.isCombo&&(form.comboItems?.length||0)<2)return;editing?await updateService(editing,form):await addService(form);setOpen(false)};
 const rating=(id:string)=>{const a=bookings.filter(b=>b.serviceId===id&&b.rating);return a.length?{avg:(a.reduce((n,b)=>n+b.rating!.stars,0)/a.length).toFixed(1),count:a.length}:null};
 const addItem=()=>{const v=item.trim();if(!v)return;setForm({...form,comboItems:[...(form.comboItems||[]),v]});setItem('')};
 return <div className="space-y-7 pb-10"><div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4"><div><p className="eyebrow">Catálogo</p><h1 className="page-title mt-2">Serviços</h1><p className="page-subtitle">Cadastre serviços e combos. A identidade visual vem da sua barbearia, sem fotos por serviço.</p></div><button onClick={()=>edit()} className="btn-primary"><Plus size={18}/>Novo serviço</button></div>
 <div className="flex flex-wrap gap-2">{presets.map(p=><button key={p} onClick={()=>{edit();setForm({...empty,name:p,isCombo:p.includes('+'),category:p.includes('+')?'Combo':p==='Barba'?'Barba':p==='Sobrancelha'?'Acabamento':'Cabelo',comboItems:p.includes('+')?p.split('+').map(x=>x.trim()):[]})}} className="px-3 py-2 rounded-xl border border-white/10 bg-white/[.03] text-xs font-semibold text-slate-300 hover:border-amber-500/40">{p}</button>)}</div>
 <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-5">{services.map(s=>{const r=rating(s.id);return <article key={s.id} className="surface p-6 flex flex-col gap-5"><div className="flex justify-between gap-4"><div className="flex gap-3"><div className="w-11 h-11 rounded-2xl bg-amber-500/10 text-amber-400 flex items-center justify-center">{s.isCombo?<Layers3 size={20}/>:<Scissors size={20}/>}</div><div><div className="text-[10px] uppercase tracking-widest text-slate-500">{s.category||'Outros'}{s.isCombo?' · Combo':''}</div><h3 className="font-bold text-lg mt-1">{s.name}</h3></div></div><div className="flex gap-1"><button onClick={()=>edit(s)} className="p-2 text-slate-400 hover:text-amber-400"><Edit2 size={16}/></button><button onClick={()=>setDeleting(s)} className="p-2 text-slate-400 hover:text-red-400"><Trash2 size={16}/></button></div></div>
 {s.description&&<p className="text-sm text-slate-400">{s.description}</p>}{s.isCombo&&<div className="flex flex-wrap gap-2">{(s.comboItems||[]).map(x=><span key={x} className="px-2.5 py-1 rounded-lg bg-white/5 text-xs text-slate-300">{x}</span>)}</div>}
 <div className="mt-auto pt-4 border-t border-white/5 flex justify-between items-center"><span className="text-xl font-bold text-amber-400">R$ {Number(s.price).toFixed(2)}</span><span className="text-sm text-slate-400 flex items-center gap-1.5"><Clock size={14}/>{s.duration} min</span></div>{r&&<div className="text-xs text-slate-500 flex items-center gap-1"><Star size={13} className="text-amber-500"/>{r.avg} · {r.count} avaliações</div>}</article>})}{!services.length&&<div className="empty-state md:col-span-2 xl:col-span-3">Seu catálogo ainda está vazio. Cadastre o primeiro serviço ou use um dos modelos acima.</div>}</div>
 {open&&<div className="fixed inset-0 z-50 flex items-center justify-center p-4"><div className="absolute inset-0 bg-slate-950/85 backdrop-blur-sm" onClick={()=>setOpen(false)}/><form onSubmit={submit} className="relative surface p-7 w-full max-w-xl max-h-[92vh] overflow-y-auto space-y-5"><div className="flex justify-between"><div><p className="eyebrow">{editing?'Editar':'Cadastrar'}</p><h2 className="section-title mt-1">Serviço da barbearia</h2></div><button type="button" onClick={()=>setOpen(false)}><X/></button></div>
 <div><label className="label">Nome do serviço</label><input required minLength={2} className="field" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Ex.: Corte degradê"/></div>
 <div className="grid sm:grid-cols-2 gap-4"><div><label className="label">Categoria</label><select className="field" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(x=><option key={x}>{x}</option>)}</select></div><label className="flex items-center gap-3 mt-6"><input type="checkbox" checked={form.isCombo===true} onChange={e=>setForm({...form,isCombo:e.target.checked,category:e.target.checked?'Combo':form.category,comboItems:e.target.checked?form.comboItems:[]})}/><span className="font-semibold">É um combo</span></label></div>
 {form.isCombo&&<div><label className="label">Itens do combo</label><div className="flex gap-2"><input className="field" value={item} onChange={e=>setItem(e.target.value)} placeholder="Ex.: Barba" onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addItem()}}}/><button type="button" onClick={addItem} className="btn-secondary"><Plus size={16}/></button></div><div className="flex flex-wrap gap-2 mt-3">{(form.comboItems||[]).map((x,i)=><button type="button" key={i} onClick={()=>setForm({...form,comboItems:form.comboItems?.filter((_,j)=>j!==i)})} className="px-3 py-1.5 rounded-lg bg-amber-500/10 text-amber-300 text-xs">{x} ×</button>)}</div>{(form.comboItems?.length||0)<2&&<p className="text-xs text-slate-500 mt-2">Adicione pelo menos dois itens ao combo.</p>}</div>}
 <div className="grid grid-cols-2 gap-4"><div><label className="label">Preço (R$)</label><input required min={0} step=".01" type="number" className="field" value={form.price} onChange={e=>setForm({...form,price:Number(e.target.value)})}/></div><div><label className="label">Duração</label><input required min={5} max={480} type="number" className="field" value={form.duration} onChange={e=>setForm({...form,duration:Number(e.target.value)})}/></div></div>
 <div><label className="label">Descrição curta (opcional)</label><textarea className="field min-h-24" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div><button disabled={form.isCombo&&(form.comboItems?.length||0)<2} className="btn-primary w-full disabled:opacity-40">{editing?'Salvar alterações':'Criar serviço'}</button></form></div>}
 {deleting&&<div className="fixed inset-0 z-[60] flex items-center justify-center p-4"><div className="absolute inset-0 bg-slate-950/90" onClick={()=>setDeleting(null)}/><div className="relative surface p-7 max-w-sm text-center"><h3 className="section-title">Desativar serviço?</h3><p className="text-sm text-slate-400 mt-3">{deleting.name} deixará de aparecer para novos agendamentos.</p><div className="flex gap-3 mt-6"><button onClick={()=>setDeleting(null)} className="btn-secondary flex-1">Cancelar</button><button onClick={async()=>{await removeService(deleting.id);setDeleting(null)}} className="flex-1 rounded-xl bg-red-500 text-white font-bold">Desativar</button></div></div></div>}</div>
};
export default AdminServices;
