import React,{useState} from 'react';
import {useApp} from '../context/AppContext';
import Logo from './Logo';
import {LayoutDashboard,Calendar,Users,Scissors,Star,Settings,LogOut,CreditCard,Clock,PlusSquare,Sun,Moon,X,Menu,ExternalLink} from 'lucide-react';

const Sidebar:React.FC<{activeTab:string;onTabChange:(tab:string)=>void}>=({activeTab,onTabChange})=>{
 const {currentUser,logout,settings,toggleTheme}=useApp();const [open,setOpen]=useState(false);const admin=currentUser?.role==='admin';
 const menu=admin?[['dashboard','Visão geral',LayoutDashboard],['bookings','Agenda',Calendar],['clients','Clientes',Users],['services','Serviços',Scissors],['reviews','Avaliações',Star],['billing','Assinatura',CreditCard],['settings','Configurações',Settings]]:[['dashboard','Meus horários',Clock],['new-booking','Agendar',PlusSquare]];
 const go=(id:string)=>{onTabChange(id);setOpen(false);window.location.hash=id};
 return <><button onClick={()=>setOpen(true)} className="lg:hidden fixed top-4 left-4 z-50 p-3 rounded-xl bg-slate-900 border border-white/10 text-white shadow-xl"><Menu size={20}/></button>{open&&<div className="lg:hidden fixed inset-0 z-40 bg-slate-950/70 backdrop-blur-sm" onClick={()=>setOpen(false)}/>}<aside className={`${open?'translate-x-0':'-translate-x-full'} lg:translate-x-0 fixed lg:static inset-y-0 left-0 z-50 w-72 lg:w-64 shrink-0 flex flex-col bg-slate-900/95 lg:bg-slate-950 border-r border-white/5 transition-transform duration-300`}>
 <div className="p-6 border-b border-white/5 flex items-center justify-between"><div className="flex items-center gap-3"><Logo size={38}/><div><div className="font-serif font-bold text-lg gradient-text">{settings.name}</div><div className="text-[9px] tracking-[.25em] uppercase text-slate-600">Management</div></div></div><button className="lg:hidden text-slate-500" onClick={()=>setOpen(false)}><X/></button></div>
 <nav className="flex-1 p-4 space-y-1.5">{menu.map(([id,label,Icon]:any)=><button key={id} onClick={()=>go(id)} className={`w-full flex items-center gap-3 px-4 py-3.5 rounded-xl text-sm font-semibold transition ${activeTab===id?'bg-amber-500 text-slate-950 shadow-lg shadow-amber-500/10':'text-slate-400 hover:bg-white/5 hover:text-white'}`}><Icon size={19}/>{label}</button>)}</nav>
 <div className="p-4 space-y-2 border-t border-white/5"><button onClick={toggleTheme} className="w-full flex items-center gap-3 px-4 py-3 rounded-xl text-sm text-slate-400 hover:bg-white/5 hover:text-white">{settings.theme==='light'?<Moon size={18}/>:<Sun size={18}/>} {settings.theme==='light'?'Modo escuro':'Modo claro'}</button><a href="#public" className="w-full flex items-center gap-3 px-4 py-3 rounded-xl text-sm text-slate-400 hover:bg-white/5 hover:text-white"><ExternalLink size={18}/> Ver site público</a><div className="p-3 rounded-xl bg-white/[.03] border border-white/5"><div className="text-[10px] text-slate-600 uppercase tracking-widest">Sessão</div><div className="text-sm font-semibold text-slate-200 truncate mt-1">{currentUser?.name}</div><div className="text-[10px] text-amber-500 uppercase font-bold mt-1">{admin?'Administrador':'Cliente'}</div></div><button onClick={logout} className="w-full flex items-center gap-3 px-4 py-3 rounded-xl text-sm text-red-400 hover:bg-red-500/10"><LogOut size={18}/> Sair</button><div className="text-center text-[9px] text-slate-700 pt-2">BarberFlow SaaS · Gestão inteligente</div></div>
 </aside></>
};
export default Sidebar;
