-- Arquivo legado intencionalmente neutralizado.
-- O BarberFlow não cria tenants, profissionais ou serviços de demonstração em produção.
-- Para validar a aplicação, crie uma barbearia real pelo Painel Master.
