import React,{createContext,useContext,useEffect,useRef,useState} from 'react';
import {User,Service,Booking,BusinessSettings,AppState,Professional} from '../types';
import {INITIAL_SERVICES,INITIAL_SETTINGS,ADMIN_USER,MOCK_CLIENT,MOCK_PROFESSIONALS} from '../constants';
interface ToastData{id:string;message:string;type:'success'|'error'|'info'|'warning'}
interface AppContextType extends AppState{
  toasts:ToastData[]; loading:boolean; tenantSlug:string;
  preSelectedServiceId:string|null;setPreSelectedServiceId:(id:string|null)=>void;preSelectedClientId:string|null;setPreSelectedClientId:(id:string|null)=>void;
  addToast:(message:string,type?:ToastData['type'])=>void;removeToast:(id:string)=>void;
  login:(email:string,password:string)=>Promise<boolean>;logout:()=>Promise<void>;register:(name:string,email:string,phone:string,password:string)=>Promise<boolean>;
  addBooking:(booking:any)=>Promise<boolean>;updateBooking:(id:string,updates:Partial<Booking>)=>Promise<void>;addReview:(id:string,stars:number,comment:string)=>Promise<void>;cancelBooking:(id:string)=>Promise<void>;
  addService:(service:Omit<Service,'id'>)=>Promise<void>;updateService:(id:string,updates:Partial<Service>)=>Promise<void>;removeService:(id:string)=>Promise<void>;updateSettings:(settings:BusinessSettings)=>Promise<void>;toggleTheme:()=>void;
  refresh:()=>Promise<void>;startCheckout:()=>Promise<string|null>;
}
const AppContext=createContext<AppContextType|undefined>(undefined);
const fallback={users:[ADMIN_USER,MOCK_CLIENT],services:INITIAL_SERVICES,professionals:MOCK_PROFESSIONALS,bookings:[],settings:INITIAL_SETTINGS};
const slugFromPath=()=>{if(window.location.pathname.startsWith('/master'))return 'platform';const m=window.location.pathname.match(/^\/b\/([^/]+)/);return m?.[1]||localStorage.getItem('bf_tenant_slug')||'barbearia-demo'};
const api=async(path:string,options:RequestInit={})=>{const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});let data:any={};try{data=await r.json()}catch{}if(!r.ok)throw new Error(data.error||'Não foi possível concluir a operação.');return data};
export const AppProvider:React.FC<{children:React.ReactNode}>=({children})=>{
 const tenantSlug=slugFromPath(); const [users,setUsers]=useState<User[]>(fallback.users);const [services,setServices]=useState<Service[]>(fallback.services);const [professionals,setProfessionals]=useState<Professional[]>(fallback.professionals);const [bookings,setBookings]=useState<Booking[]>([]);const [settings,setSettings]=useState<BusinessSettings>(fallback.settings);const [currentUser,setCurrentUser]=useState<User|null>(null);const [loading,setLoading]=useState(true);const [toasts,setToasts]=useState<ToastData[]>([]);const [preSelectedServiceId,setPreSelectedServiceId]=useState<string|null>(null);const [preSelectedClientId,setPreSelectedClientId]=useState<string|null>(null);const notified=useRef<Set<string>>(new Set());
 const addToast=(message:string,type:ToastData['type']='info')=>setToasts(p=>[...p,{id:crypto.randomUUID?.()||Math.random().toString(36),message,type}]);const removeToast=(id:string)=>setToasts(p=>p.filter(t=>t.id!==id));
 const refresh=async()=>{try{const data=await api('/api/tenant');setCurrentUser(data.currentUser);setUsers(data.users||[]);setServices(data.services||[]);setProfessionals(data.professionals||[]);setBookings(data.bookings||[]);setSettings(data.settings||INITIAL_SETTINGS);}catch(e){try{const p=await api(`/api/public?slug=${encodeURIComponent(tenantSlug)}`);setServices(p.services||[]);setProfessionals(p.professionals||[]);setSettings({...INITIAL_SETTINGS,...p.tenant,name:p.tenant.name,phone:p.tenant.phone||'',whatsapp:p.tenant.whatsapp||'',email:p.tenant.email||'',address:p.tenant.address||'',description:p.tenant.description||'',instagram:p.tenant.instagram||'',openTime:p.tenant.open_time||INITIAL_SETTINGS.openTime,closeTime:p.tenant.close_time||INITIAL_SETTINGS.closeTime,bookingInterval:p.tenant.booking_interval||30,cancellationHours:p.tenant.cancellation_hours||2,offDays:p.tenant.off_days||[]});}catch{addToast('Não foi possível conectar ao banco. Use o arquivo .env.example e configure o Railway.','warning');}}finally{setLoading(false)}};
 useEffect(()=>{localStorage.setItem('bf_tenant_slug',tenantSlug);refresh()},[]);
 useEffect(()=>{document.documentElement.classList.toggle('dark',settings.theme!=='light')},[settings.theme]);
 useEffect(()=>{const timer=setInterval(()=>{if(!currentUser)return;const now=new Date(),limit=new Date(now.getTime()+3600000);bookings.forEach(b=>{if(b.userId===currentUser.id&&b.status==='confirmed'&&!notified.current.has(b.id)){const dt=new Date(`${b.date}T${b.time}`);if(dt>now&&dt<=limit){addToast(`Lembrete: ${b.serviceName} às ${b.time}.`,'warning');notified.current.add(b.id)}}})},60000);return()=>clearInterval(timer)},[currentUser,bookings]);
 const login=async(email:string,password:string)=>{try{const d=await api('/api/auth/login',{method:'POST',body:JSON.stringify({email,password,slug:tenantSlug})});setCurrentUser(d.user);await refresh();addToast(`Bem-vindo, ${d.user.name.split(' ')[0]}!`,'success');return true}catch(e:any){addToast(e.message,'error');return false}};
 const logout=async()=>{await api('/api/auth/logout',{method:'POST'}).catch(()=>{});setCurrentUser(null);addToast('Sessão encerrada.','info')};
 const register=async(name:string,email:string,phone:string,password:string)=>{try{const d=await api('/api/auth/register',{method:'POST',body:JSON.stringify({name,email,phone,password,slug:tenantSlug})});setCurrentUser(d.user);await refresh();addToast('Conta criada com sucesso!','success');return true}catch(e:any){addToast(e.message,'error');return false}};
 const addBooking=async(data:any)=>{try{await api('/api/tenant/bookings',{method:'POST',body:JSON.stringify({...data,userId:data.userId||currentUser?.id})});await refresh();addToast('Agendamento criado! Aguarde a confirmação da barbearia.','success');return true}catch(e:any){addToast(e.message,'error');return false}};
 const updateBooking=async(id:string,updates:Partial<Booking>)=>{try{await api('/api/tenant/bookings',{method:'PATCH',body:JSON.stringify({id,...updates,paymentMethod:updates.paymentMethod,ratingStars:updates.rating?.stars,ratingComment:updates.rating?.comment})});await refresh();}catch(e:any){addToast(e.message,'error')}};
 const addReview=async(id:string,stars:number,comment:string)=>{await updateBooking(id,{rating:{stars,comment,date:new Date().toISOString()}});addToast('Avaliação registrada. Obrigado!','success')};
 const cancelBooking=async(id:string)=>{await updateBooking(id,{status:'cancelled'});addToast('Agendamento cancelado.','warning')};
 const addService=async(s:Omit<Service,'id'>)=>{try{await api('/api/tenant/services',{method:'POST',body:JSON.stringify(s)});await refresh();addToast('Serviço adicionado.','success')}catch(e:any){addToast(e.message,'error')}};
 const updateService=async(id:string,u:Partial<Service>)=>{try{await api('/api/tenant/services',{method:'PUT',body:JSON.stringify({id,...u})});await refresh();addToast('Serviço atualizado.','success')}catch(e:any){addToast(e.message,'error')}};
 const removeService=async(id:string)=>{await updateService(id,{active:false});addToast('Serviço desativado.','info')};
 const updateSettings=async(s:BusinessSettings)=>{try{await api('/api/tenant',{method:'PUT',body:JSON.stringify({kind:'settings',settings:s})});setSettings(s);addToast('Configurações salvas.','success')}catch(e:any){addToast(e.message,'error')}};
 const toggleTheme=()=>{const next=settings.theme==='light'?'dark':'light';setSettings(p=>({...p,theme:next}));updateSettings({...settings,theme:next})};
 const startCheckout=async()=>{try{const d=await api('/api/billing/checkout',{method:'POST'});return d.url||null}catch(e:any){addToast(e.message,'error');return null}};
 return <AppContext.Provider value={{users,services,professionals,bookings,settings,currentUser,toasts,loading,tenantSlug,preSelectedServiceId,setPreSelectedServiceId,preSelectedClientId,setPreSelectedClientId,addToast,removeToast,login,logout,register,addBooking,updateBooking,addReview,cancelBooking,addService,updateService,removeService,updateSettings,toggleTheme,refresh,startCheckout}}>{children}</AppContext.Provider>
};
export const useApp=()=>{const c=useContext(AppContext);if(!c)throw new Error('useApp must be used within AppProvider');return c};
