import React from 'react';
import {ArrowRight,CalendarDays,CheckCircle2,Clock3,MapPin,Phone,Scissors,Instagram,MessageCircle,Layers3,Gift} from 'lucide-react';
import {useApp} from '../context/AppContext';
import Logo from '../components/Logo';

const PublicHome:React.FC<{onLogin:()=>void;onBook:()=>void}>=({onLogin,onBook})=>{
 const {settings,services,professionals}=useApp();
 const active=services.filter(s=>s.active!==false);
 const whatsapp=settings.whatsapp?`https://wa.me/${settings.whatsapp.replace(/\D/g,'')}`:'';
 return <div className="min-h-screen bg-slate-950 text-white">
  <header className="sticky top-0 z-40 bg-slate-950/80 backdrop-blur-xl border-b border-white/5"><div className="max-w-7xl mx-auto px-5 lg:px-8 h-20 flex items-center justify-between">
   <div className="flex items-center gap-3">{settings.logoUrl?<img src={settings.logoUrl} alt="" className="w-10 h-10 rounded-xl object-cover border border-white/10"/>:<Logo size={38}/>}<div><div className="text-xl font-bold tracking-tight gradient-text">{settings.name}</div><div className="text-[9px] tracking-[.25em] uppercase text-slate-500">Agendamento online</div></div></div>
   <div className="flex items-center gap-3"><button onClick={onLogin} className="hidden sm:block px-4 py-2.5 rounded-xl text-sm font-semibold text-slate-300 hover:text-white">Entrar</button><button onClick={onBook} className="btn-primary">Agendar horário</button></div>
  </div></header>
  <main>
   <section className="relative overflow-hidden bg-slate-950" style={settings.coverUrl?{backgroundImage:`linear-gradient(rgba(2,6,23,.78),rgba(2,6,23,.96)),url(${settings.coverUrl})`,backgroundSize:'cover',backgroundPosition:'center'}:undefined}>
    <div className="relative max-w-7xl mx-auto px-5 lg:px-8 py-24 lg:py-32 grid lg:grid-cols-[1.15fr_.85fr] gap-12 items-center">
     <div><div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full border border-amber-500/20 bg-amber-500/10 text-amber-400 text-xs font-bold uppercase tracking-widest mb-6"><CalendarDays size={13}/> Agenda oficial</div>
      <h1 className="text-5xl lg:text-7xl font-extrabold tracking-[-.045em] leading-[.98]">{settings.name}</h1><p className="mt-6 text-lg text-slate-300 max-w-xl leading-relaxed">{settings.description||'Escolha seu serviço, profissional e um horário disponível.'}</p>
      <div className="mt-8 flex flex-wrap gap-3"><button onClick={onBook} className="px-6 py-4 rounded-2xl bg-amber-500 text-slate-950 font-extrabold flex items-center gap-2">Agendar agora <ArrowRight size={19}/></button>{whatsapp&&<a href={whatsapp} target="_blank" rel="noreferrer" className="px-6 py-4 rounded-2xl border border-white/10 bg-white/5 font-bold flex items-center gap-2"><MessageCircle size={19}/>WhatsApp</a>}</div>
      <div className="mt-10 flex flex-wrap gap-6 text-sm text-slate-400">{settings.openTime&&settings.closeTime&&<span className="flex items-center gap-2"><Clock3 size={16} className="text-amber-500"/>{settings.openTime} — {settings.closeTime}</span>}{settings.address&&<span className="flex items-center gap-2"><MapPin size={16} className="text-amber-500"/>{settings.address}</span>}</div>
     </div>
     <div className="surface p-6 bg-slate-950/60"><p className="eyebrow">Equipe</p><h2 className="text-2xl font-bold mt-2">Escolha seu profissional</h2><div className="grid grid-cols-2 gap-3 mt-6">{professionals.slice(0,4).map(p=><div key={p.id} className="rounded-2xl border border-white/10 bg-white/[.04] p-4"><div className="w-10 h-10 rounded-full bg-amber-500/10 text-amber-400 flex items-center justify-center"><Scissors size={18}/></div><div className="font-bold mt-3">{p.name}</div><div className="text-xs text-slate-500 mt-1">{p.specialty||p.role||'Barbeiro'}</div></div>)}</div>{!professionals.length&&<p className="text-sm text-slate-500 mt-5">A equipe será exibida assim que a barbearia cadastrar seus profissionais.</p>}</div>
    </div>
   </section>
   <section className="max-w-7xl mx-auto px-5 lg:px-8 py-20"><div className="text-center max-w-2xl mx-auto mb-12"><p className="eyebrow">Serviços</p><h2 className="text-4xl font-bold mt-3">Escolha o seu atendimento</h2><p className="text-slate-400 mt-3">Serviços e combos cadastrados diretamente pela barbearia.</p></div>
    <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5">{active.map(s=><article key={s.id} className="surface p-6 hover:-translate-y-1 transition"><div className="flex items-start justify-between gap-4"><div className="w-11 h-11 rounded-2xl bg-amber-500/10 text-amber-400 flex items-center justify-center">{s.isCombo?<Layers3 size={20}/>:<Scissors size={20}/>}</div><span className="text-[10px] uppercase tracking-widest text-slate-500">{s.category||'Serviço'}</span></div><h3 className="font-bold text-xl mt-5">{s.name}</h3>{s.description&&<p className="text-sm text-slate-400 mt-2">{s.description}</p>}{s.isCombo&&<div className="flex flex-wrap gap-2 mt-4">{(s.comboItems||[]).map(x=><span key={x} className="px-2.5 py-1 rounded-lg bg-white/5 text-xs text-slate-300">{x}</span>)}</div>}<div className="mt-6 pt-4 border-t border-white/5 flex justify-between"><span className="font-bold text-amber-400">R$ {Number(s.price).toFixed(2)}</span><span className="text-slate-500 text-sm">{s.duration} min</span></div></article>)}{!active.length&&<div className="empty-state col-span-full">O catálogo ainda não está disponível.</div>}</div>
   </section>
   {settings.loyaltyEnabled&&<section className="border-y border-white/5 bg-slate-900/50"><div className="max-w-7xl mx-auto px-5 lg:px-8 py-12 flex gap-5 items-center"><div className="w-12 h-12 rounded-2xl bg-amber-500/10 text-amber-400 flex items-center justify-center"><Gift/></div><div><p className="font-bold">Programa de fidelidade</p><p className="text-sm text-slate-400 mt-1">A cada {settings.loyaltyTarget||10} atendimentos, {settings.loyaltyReward||'consulte a recompensa oferecida pela barbearia'}.</p></div></div></section>}
   <section className="max-w-7xl mx-auto px-5 lg:px-8 py-14 grid md:grid-cols-3 gap-6 text-center">{[['Agendamento online',CalendarDays],['Escolha seu profissional',Scissors],['Horários reais disponíveis',CheckCircle2]].map(([label,Icon])=>{const I=Icon as any;return <div key={String(label)}><I className="mx-auto text-amber-500" size={27}/><h3 className="font-bold mt-3">{label as string}</h3></div>})}</section>
  </main>
  <footer className="border-t border-white/5"><div className="max-w-7xl mx-auto px-5 lg:px-8 py-10 flex flex-col md:flex-row justify-between gap-6 text-sm text-slate-500"><div><span className="text-white font-semibold">{settings.name}</span>{settings.email&&<p className="mt-2">{settings.email}</p>}</div><div className="flex gap-5 items-center">{whatsapp&&<a href={whatsapp} target="_blank" rel="noreferrer"><Phone size={17}/></a>}{settings.instagram&&<a href={`https://instagram.com/${settings.instagram.replace('@','')}`} target="_blank" rel="noreferrer"><Instagram size={17}/></a>}{settings.phone&&<span>{settings.phone}</span>}</div></div></footer>
 </div>
};
export default PublicHome;
