import React,{useEffect,useMemo,useState} from 'react';
import {Building2,ExternalLink,LogOut,Plus,RefreshCw,Search,ShieldCheck,Store,UsersRound} from 'lucide-react';
import {useApp} from '../../context/AppContext';
const MasterDashboard:React.FC=()=>{
 const {logout,addToast}=useApp();const [tenants,setTenants]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [search,setSearch]=useState('');
 const [form,setForm]=useState({name:'',slug:'',ownerName:'',ownerEmail:'',ownerPassword:'',phone:'',whatsapp:''});
 const load=async()=>{setLoading(true);try{const r=await fetch('/api/master/tenants');const d=await r.json();if(!r.ok)throw new Error(d.error||'Falha ao carregar.');setTenants(Array.isArray(d)?d:[])}catch(e:any){addToast(e.message,'error')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const create=async(e:React.FormEvent)=>{e.preventDefault();try{const r=await fetch('/api/master/tenants',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw new Error(d.error);addToast('Barbearia criada.','success');setForm({name:'',slug:'',ownerName:'',ownerEmail:'',ownerPassword:'',phone:'',whatsapp:''});load()}catch(e:any){addToast(e.message,'error')}};
 const filtered=useMemo(()=>tenants.filter(t=>t.name?.toLowerCase().includes(search.toLowerCase())||t.slug?.toLowerCase().includes(search.toLowerCase())),[tenants,search]);
 const active=tenants.filter(t=>['active','trialing'].includes(t.subscriptionStatus)).length;const clients=tenants.reduce((s,t)=>s+Number(t.users||0),0);
 return <div className="min-h-screen bg-slate-950 text-white"><header className="border-b border-white/[.06] bg-slate-950/90 backdrop-blur-xl sticky top-0 z-30"><div className="max-w-[1500px] mx-auto px-5 lg:px-10 h-20 flex items-center justify-between"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-xl bg-amber-500 text-slate-950 flex items-center justify-center"><ShieldCheck size={21}/></div><div><div className="font-bold">BarberFlow</div><div className="text-[9px] uppercase tracking-[.25em] text-slate-600">Platform Console</div></div></div><button onClick={logout} className="btn-secondary !py-2.5 !px-4"><LogOut size={16}/>Sair</button></div></header>
 <main className="max-w-[1500px] mx-auto px-5 lg:px-10 py-8 lg:py-12 space-y-8">
  <div className="flex flex-col lg:flex-row lg:items-end justify-between gap-5"><div><p className="eyebrow">Visão da plataforma</p><h1 className="page-title mt-2">Operação BarberFlow</h1><p className="page-subtitle">Acompanhe tenants e crie novas operações sem dados de demonstração.</p></div><button onClick={load} className="btn-secondary"><RefreshCw size={17}/>Atualizar</button></div>
  <div className="grid sm:grid-cols-3 gap-4">{[[Building2,'Barbearias',tenants.length],[Store,'Ativas / trial',active],[UsersRound,'Usuários cadastrados',clients]].map(([Icon,label,value]:any)=><div key={label} className="surface p-5"><div className="flex items-center justify-between"><span className="text-xs uppercase tracking-wider font-bold text-slate-500">{label}</span><Icon size={19} className="text-amber-500"/></div><div className="text-3xl font-bold mt-4">{value}</div></div>)}</div>
  <div className="grid xl:grid-cols-[1.7fr_.8fr] gap-6"><section className="surface overflow-hidden"><div className="p-6 border-b border-white/[.06] flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><h2 className="section-title">Barbearias</h2><p className="text-xs text-slate-500 mt-1">Tenants cadastrados na plataforma</p></div><div className="relative"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-600"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar barbearia..." className="field !pl-9 sm:w-64"/></div></div>
   <div className="overflow-x-auto">{loading?<div className="py-20 text-center text-slate-500">Carregando operação...</div>:filtered.length?<table className="w-full text-sm"><thead><tr className="text-left text-[10px] uppercase tracking-wider text-slate-600 border-b border-white/[.05]"><th className="px-6 py-4">Barbearia</th><th>Status</th><th>Usuários</th><th>Criada</th><th></th></tr></thead><tbody>{filtered.map(t=><tr key={t.id} className="border-b border-white/[.04] hover:bg-white/[.02]"><td className="px-6 py-4"><div className="font-bold">{t.name}</div><div className="text-xs text-slate-600 mt-1">/b/{t.slug}</div></td><td><span className={`px-2.5 py-1 rounded-full text-[10px] font-bold uppercase ${['active','trialing'].includes(t.subscriptionStatus)?'bg-emerald-500/10 text-emerald-400':'bg-slate-800 text-slate-400'}`}>{t.subscriptionStatus}</span></td><td className="text-slate-400">{t.users}</td><td className="text-slate-500">{new Date(t.createdAt).toLocaleDateString('pt-BR')}</td><td className="pr-6"><a href={`/b/${t.slug}`} target="_blank" className="text-slate-500 hover:text-amber-400"><ExternalLink size={16}/></a></td></tr>)}</tbody></table>:<div className="m-6 empty-state">Nenhuma barbearia encontrada.</div>}</div>
  </section>
  <section className="surface p-6 h-fit"><div className="w-11 h-11 rounded-2xl bg-amber-500/10 text-amber-400 flex items-center justify-center"><Plus size={21}/></div><h2 className="section-title mt-5">Nova barbearia</h2><p className="text-xs text-slate-500 mt-1">Cria o tenant e seu administrador inicial.</p><form onSubmit={create} className="space-y-3 mt-6">{[['name','Nome da barbearia'],['slug','Slug da URL'],['ownerName','Nome do responsável'],['ownerEmail','E-mail do responsável'],['ownerPassword','Senha inicial'],['phone','Telefone'],['whatsapp','WhatsApp']].map(([k,p])=><input key={k} required={['name','slug','ownerName','ownerEmail','ownerPassword'].includes(k)} minLength={k==='ownerPassword'?8:undefined} type={k==='ownerPassword'?'password':k==='ownerEmail'?'email':'text'} placeholder={p} value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})} className="field"/>)}<button className="btn-primary w-full"><Plus size={17}/>Criar operação</button></form></section></div>
 </main></div>
};
export default MasterDashboard;